version: '3.3'
services:

  django:
    image: s3eventscrapper_django:dev
    build:
      context: .
      args:
        release: dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    env_file:
      - develop.env
      - local.env
    environment:
      - COMMAND=runserver
    ports:
      - 8000:8000
    depends_on:
      - redis

volumes:
  django-media:
  django-static:

networks:
  default:
    driver: bridge
