version: '3.3'
services:

  django:
    image: s3eventscrapper_django:dev
    build:
      context: .
      args:
        release: dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    env_file:
      - develop.env
      - local.env
    environment:
      - COMMAND=runserver
    ports:
      - 8000:8000
    depends_on:
      - redis

  worker:
    image: s3eventscrapper_django:dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    env_file:
      - develop.env
      - local.env
    environment:
      - COMMAND=worker
    depends_on:
      - django

  celerybeat:
    image: s3eventscrapper_django:dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    env_file:
      - develop.env
      - local.env
    environment:
      - COMMAND=celerybeat
    depends_on:
      - django

  redis:
    image: redis:3.2.10
    volumes:
      - redis-data:/data

  celeryflower:
    image: s3eventscrapper_django:dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    env_file:
      - develop.env
      - local.env
    environment:
      - COMMAND=celeryflower
    ports:
      - 5555:5555
    depends_on:
      - django

  pgadmin:
      image: dpage/pgadmin4:latest
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - 8082:80

volumes:
  django-media:
  django-static:
  redis-data:

networks:
  default:
    driver: bridge
