# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import s3pooler.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3pooler', '0002_auto_20181025_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonevents',
            name='inserted_at',
            field=models.DateTimeField(default=s3pooler.models.utc_now),
        ),
    ]
